[package]
name = "tiberius"
description = "A TDS (MSSQL) driver"
version = "0.3.2"
readme = "../README.md"
repository = "https://github.com/steffengy/tiberius"
authors = ["Steffen Butzer <steffen.butzer@outlook.com>"]
documentation = "https://docs.rs/tiberius/"
keywords = ["tds", "mssql"]
license = "MIT/Apache-2.0"

[dependencies]
bitflags = "1.0"
byteorder = "1.0"
bytes = "0.4.3"
encoding = "0.2"
fnv = "1.0"
lazy_static = "1.0"
futures = "0.1.18"
tokio = "0.1.2"
futures-state-stream = "0.1"
chrono = { version = "0.4.0", optional = true }
winauth = { version = "0.0.3" }
native-tls = { version = "0.2.1", optional = true }
tokio-tls = { version = "0.2", optional = true }

[features]
default = ["chrono", "tls"]
tls = ["tokio-tls", "native-tls"]
